import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#2fd9f4',
        'secondary-container': '#7701d0',
        'surface-container-low': '#161b29',
        'surface-container-lowest': '#090e1b',
        'tertiary-fixed': '#a2eeff',
        'on-primary-fixed': '#002021',
        'on-tertiary-fixed-variant': '#004e5a',
        'on-tertiary': '#00363e',
        'primary': '#e9feff',
        'inverse-on-surface': '#2b303e',
        'on-secondary-fixed-variant': '#6700b5',
        'secondary-fixed-dim': '#dcb8ff',
        'on-secondary-fixed': '#2c0051',
        'inverse-primary': '#00696e',
        'secondary': '#dcb8ff',
        'on-tertiary-fixed': '#001f25',
        'on-surface-variant': '#b9caca',
        'tertiary-container': '#8cebff',
        'surface-tint': '#00dce5',
        'on-tertiary-container': '#006b7a',
        'inverse-surface': '#dee2f5',
        'outline-variant': '#3a494a',
        'on-primary': '#003739',
        'on-secondary': '#480081',
        'surface': '#0e1320',
        'surface-variant': '#303443',
        'surface-dim': '#0e1320',
        'error-container': '#93000a',
        'on-error': '#690005',
        'surface-container-high': '#252a38',
        'primary-fixed': '#63f7ff',
        'primary-container': '#00f5ff',
        'on-background': '#dee2f5',
        'surface-container': '#1a1f2d',
        'on-surface': '#dee2f5',
        'error': '#ffb4ab',
        'secondary-fixed': '#efdbff',
        'on-primary-container': '#006c71',
        'surface-bright': '#343948',
        'background': '#0e1320',
        'surface-container-highest': '#303443',
        'outline': '#849495',
        'tertiary': '#f0fcff',
        'primary-fixed-dim': '#00dce5',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004f53',
        'on-secondary-container': '#dcb7ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontFamily: {
        headline: ['"Manrope"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
        label: ['"Inter"', 'sans-serif'],
      },
      animation: {
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
};

export default config;
